language: erlang
otp_release:
  - R16B02
script:
  - ./rebar compile
  - ./rebar eunit skip_deps=true
  - ./rebar xref skip_deps=true
notifications:
  webhooks:
    - https://wooga.slack.com/services/hooks/travis?token=mZNldRc90aXkhWxx71FKPuPN
